apiVersion: v1
kind: Service
metadata:
  name: dns-app
spec:
  type: NodePort
  selector:
    app: dns-app
  ports:
  - name: as
    protocol: TCP
    #protocol: UDP
    nodePort: 30001
    port: 9091
    targetPort: 9091
  - name: fs
    protocol: TCP
    nodePort: 30002
    port: 9090
    targetPort: 9090
  - name: us
    protocol: TCP
    nodePort: 30003
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-app
  template:
    metadata:
      labels:
        app: dns-app
    spec:
      containers:
      - name: as
        image: docker.io/dp3278/as:latest
        ports:
        - containerPort: 9091
      - name: fs
        image: docker.io/dp3278/fs:latest
        ports:
        - containerPort: 9090
      - name: us
        image: docker.io/dp3278/us:latest
        ports:
        - containerPort: 8080